name: articlett_schule_webpage
description: A new Jaspr project
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  jaspr: ^0.22.1
  jaspr_router: ^0.8.1
  jaspr_flutter_embed: ^0.4.10
  flutter_test_app:
    path: ../flutter_test_app

dev_dependencies:
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  build_web_compilers: ^4.4.6
  jaspr_builder: ^0.22.1
  jaspr_lints: ^0.6.0
  lints: ^6.0.0
  
jaspr:
  mode: static
  flutter: embedded # or 'plugins' for plugin support

flutter:
  uses-material-design: true