name: articlett_schule_webpage
description: A new Jaspr project
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  jaspr: ^0.21.7
  jaspr_router: ^0.8.0
  jaspr_flutter_embed: ^0.4.9
  flutter_test_app:
    path: ../flutter_test_app

dev_dependencies:
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  jaspr_web_compilers: ^4.3.2+1
  jaspr_builder: ^0.21.7
  jaspr_lints: ^0.5.1
  lints: ^5.0.0
  
jaspr:
  mode: static

flutter:
  uses-material-design: true